// angular/apis/messages/src/app/components/login/login-form/login-form.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { UsersService } from 'src/app/services/users.service';

@Component({
  selector: 'login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.css']
})
export class LoginFormComponent implements OnInit {

  username: string;
  password: string;
  errorMessage: string;

  constructor(private usersService: UsersService,
    private router: Router) { }

  ngOnInit(): void {
  }

  onSubmit(form: NgForm) {
    this.usersService.attemptLogin(form.value.username, form.value.password)
      .subscribe(data => {
        // login successful
        this.usersService.setActiveUser(data as any);
        this.router.navigate([""]);
      }, error => {
        if (error.status == 500) {
          // total error
          this.errorMessage = "Uh oh! :( Something went wrong... Try Again."
        } else {
          // 401
          console.log(error);
          this.errorMessage = error.error.message;
        }
      });
  }

}

<div class="root">

    <h1>Log In</h1>

    <form #form="ngForm"
          (ngSubmit)="onSubmit(form)">

        <div class="input username">
            <input type="text"
                   name="username"
                   [(ngModel)]="username"
                   placeholder="username"
                   required>
        </div>

        <div class="input password">
            <input type="password"
                   name="password"
                   [(ngModel)]="password"
                   placeholder="password"
                   required>
        </div>

        <button type="submit"
                [disabled]="form.invalid">Log In</button>
        <p class="error">{{errorMessage}}</p>
        <hr>

        <a routerLink="../signup">
            <button type="button">Sign Up</button>
        </a>
    </form>
</div>

// react/7-forms/src/components/LoginForm.js
import React, { useState } from 'react';
import './LoginForm.css';

export default function LoginForm() {

    const [formData, setFormData] = useState({
        username: '',
        password: ''
    })

    function onInputChanged(e) {
        let value = e.target.value
        let name = e.target.name

        setFormData({
            ...formData,
            [name]: value
        });
    }

    function attemptLogIn(e) {
        e.preventDefault();
        console.log(formData);
    }

    return (
        <form className="login-form"
            onSubmit={attemptLogIn}
        >
            <h3>Log In</h3>

            <div>
                <label htmlFor="username">
                    Username :
                </label>
                <input
                    type="text"
                    name="username"
                    value={formData.username}
                    onChange={onInputChanged}

                    placeholder="username"
                    id="username"
                    required
                />
            </div>

            <div>
                <label htmlFor="password">
                    Password :
                </label>
                <input
                    type="password"
                    name="password"
                    value={formData.password}
                    onChange={onInputChanged}

                    placeholder="password"
                    id="password"
                    required
                />
            </div>

            <button
                type="submit"
                disabled={!formData.username || !formData.password}
            >
                Log In
            </button>
        </form>
    );
}
